version: v1.0
name: Prod
blocks:
  - name: Deploy
    task:
      jobs:
        - name: Parallel Deploys
          commands:
            - echo "job 1"
          parallelism: 5
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
