version: v1.0
name: staging
blocks:
  - name: Deploy
    task:
      jobs:
        - name: 'Job #1'
          commands:
            - echo "job 1"
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
