version: "v1.0"
name: Staging
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

promotions:
  - name: preproduction
    pipeline_file: preproduction.yml

blocks:
  - name: "A"
    dependencies: []
    task:
      jobs:
      - name: "A1"
        commands:
          - sleep 10
      - name: "A2"
        commands:
          - sleep 10
      - name: "A3"
        commands:
          - sleep 10
  - name: "B"
    dependencies: ["A"]
    task:
      jobs:
      - name: "B"
        commands:
          - sleep 10
  - name: "C"
    dependencies: ["B"]
    task:
      jobs:
      - name: "C"
        commands:
          - sleep 10
